### ISSUE TITLE
UX improvement for notes!

### ISSUE THREAD

**Issue by Shiyadh123** [ObaidKhan625/DSAndeavour#36]
As of now, the user has no idea whether he has kept some notes for a particular problem or not though we have the notes feature for each question.

It would be great if we have some indication on the notes icon(at the top right) on the problem card so that the user would get the info on whether some note has been written there or not. Otherwise, the user has to open the note and check for that, irrespective of having a previous note. 

My suggestion:  Change the color of the note icon (eg: Green) as long as the note is not an empty string. So, the user will get an idea about having a note on the problem card itself, without checking for that explicitly.

**Comment by ObaidKhan625** [comment]
Great Idea! I've added this. The note icon for an added note is now different from an empty one.

**Comment by Shiyadh123** [comment]
Great!
Thanks for the quick response.
